---
- name: Generate /etc/ssh/ssh_config file
  ansible.builtin.template:
    src: ssh.conf.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: '0644'

- name: Generate client configuration files
  ansible.builtin.template:
    src: ssh.conf.d.j2
    dest: '/etc/ssh/ssh_config.d/{{ item.name }}.conf'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ catena_ssh_client }}'
