---
#
# Configuration: OpenSSH 9.0
# Compatibility: OpenSSH 7.4+, Dropbear SSH 2018.76+
#

# List of hostkeys for OpenSSH >= 6.3
catena_ssh_host_key_files:
  - /etc/ssh/ssh_host_rsa_key
  - /etc/ssh/ssh_host_ecdsa_key
  - /etc/ssh/ssh_host_ed25519_key

# Public key algorithms for OpenSSH >= 6.5
# Check with: `ssh -Q HostKeyAlgorithms`
catena_ssh_host_key_algorithms:
  # since OpenSSH 6.5
  - ssh-ed25519
  # since OpenSSH 7.2
  - rsa-sha2-512
  - rsa-sha2-256

# Ciphers for OpenSSH >= 6.5
# Check with: `ssh -Q cipher`
catena_ssh_ciphers:
  # since OpenSSH 6.5, default since OpenSSH 6.9
  - chacha20-poly1305@openssh.com
  # since OpenSSH 6.2
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  # since OpenSSH 3.7
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

# Hash algorithms for OpenSSH >= 6.2
# Check with: `ssh -Q mac`
catena_ssh_macs:
  # since OpenSSH 6.2
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - umac-128-etm@openssh.com

# Key Exchange Algorithms
catena_ssh_kex:
  # since OpenSSH 7.4
  - curve25519-sha256
  # since OpenSSH 7.3
  - diffie-hellman-group18-sha512
  - diffie-hellman-group16-sha512
  - diffie-hellman-group14-sha256
  # since OpenSSH 6.5
  - curve25519-sha256@libssh.org
  # since OpenSSH 4.4
  - diffie-hellman-group-exchange-sha256
